apiVersion: apps/v1
kind: Deployment
metadata:
  name: monty-orchestrator
  namespace: monty-sim
  labels:
    app: monty-orchestrator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: monty-orchestrator
  template:
    metadata:
      labels:
        app: monty-orchestrator
    spec:
      serviceAccountName: run-manager
      containers:
      - name: orchestrator
        image: monty-orchestrator:latest
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: K8S_NAMESPACE
          value: "monty-sim"
        - name: S3_CHECKPOINTS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: orchestrator-config
              key: checkpoints-bucket
        - name: S3_ARTIFACTS_BUCKET
          valueFrom:
            configMapKeyRef:
              name: orchestrator-config
              key: artifacts-bucket
        - name: ECR_REGISTRY
          valueFrom:
            configMapKeyRef:
              name: orchestrator-config
              key: ecr-registry
        - name: AWS_REGION
          valueFrom:
            configMapKeyRef:
              name: orchestrator-config
              key: aws-region
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: monty-orchestrator-service
  namespace: monty-sim
spec:
  selector:
    app: monty-orchestrator
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: orchestrator-config
  namespace: monty-sim
data:
  checkpoints-bucket: "monty-checkpoints-dev"
  artifacts-bucket: "sim-artifacts-dev"
  ecr-registry: "123456789012.dkr.ecr.us-east-1.amazonaws.com"
  aws-region: "us-east-1"
