# brain-profiles/large.yaml
cortex:
  sensory_areas:
    - name: vision
      columns: 4096
      cells_per_column: 32
    - name: proprioception
      columns: 2048
      cells_per_column: 32
  associative_areas:
    - name: multimodal
      columns: 8192
      cells_per_column: 32
  motor_area:
    columns: 4096
    cells_per_column: 32
  synapse_density: 0.12
  learning_rate: 0.0007
